//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.28 at 05:22:27 PM IST 
//


package io.github.soheshts.mycart.jaxb;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="category" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="categoryName"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="item" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="itemId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="categoryId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="availableStock" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *                             &lt;element name="sellingPrice" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "category"
})
@XmlRootElement(name = "inventory")
public class Inventory {

    @XmlElement(required = true)
    protected List<Category> category;

    /**
     * Gets the value of the category property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the category property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCategory().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Category }
     */
    public List<Category> getCategory() {
        if (category == null) {
            category = new ArrayList<Category>();
        }
        return this.category;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="categoryName"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="item" maxOccurs="unbounded"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="itemId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="categoryId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="availableStock" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
     *                   &lt;element name="sellingPrice" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "categoryName",
            "item"
    })
    public static class Category {

        @XmlElement(required = true)
        protected CategoryName categoryName;
        @XmlElement(required = true)
        protected List<Item> item;
        @XmlAttribute(name = "id", required = true)
        protected String id;

        /**
         * Gets the value of the categoryName property.
         *
         * @return possible object is
         * {@link CategoryName }
         */
        public CategoryName getCategoryName() {
            return categoryName;
        }

        /**
         * Sets the value of the categoryName property.
         *
         * @param value allowed object is
         *              {@link CategoryName }
         */
        public void setCategoryName(CategoryName value) {
            this.categoryName = value;
        }

        /**
         * Gets the value of the item property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the item property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getItem().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Item }
         */
        public List<Item> getItem() {
            if (item == null) {
                item = new ArrayList<Item>();
            }
            return this.item;
        }

        /**
         * Gets the value of the id property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setId(String value) {
            this.id = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class CategoryName {

            @XmlAttribute(name = "name", required = true)
            protected String name;

            /**
             * Gets the value of the name property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setName(String value) {
                this.name = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="itemId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="categoryId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="availableStock" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
         *         &lt;element name="sellingPrice" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "itemId",
                "categoryId",
                "availableStock",
                "sellingPrice"
        })
        public static class Item {

            @XmlElement(required = true)
            protected String itemId;
            @XmlElement(required = true)
            protected String categoryId;
            @XmlElement(required = true)
            protected BigInteger availableStock;
            @XmlElement(required = true)
            protected BigInteger sellingPrice;

            /**
             * Gets the value of the itemId property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getItemId() {
                return itemId;
            }

            /**
             * Sets the value of the itemId property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setItemId(String value) {
                this.itemId = value;
            }

            /**
             * Gets the value of the categoryId property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getCategoryId() {
                return categoryId;
            }

            /**
             * Sets the value of the categoryId property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setCategoryId(String value) {
                this.categoryId = value;
            }

            /**
             * Gets the value of the availableStock property.
             *
             * @return possible object is
             * {@link BigInteger }
             */
            public BigInteger getAvailableStock() {
                return availableStock;
            }

            /**
             * Sets the value of the availableStock property.
             *
             * @param value allowed object is
             *              {@link BigInteger }
             */
            public void setAvailableStock(BigInteger value) {
                this.availableStock = value;
            }

            /**
             * Gets the value of the sellingPrice property.
             *
             * @return possible object is
             * {@link BigInteger }
             */
            public BigInteger getSellingPrice() {
                return sellingPrice;
            }

            /**
             * Sets the value of the sellingPrice property.
             *
             * @param value allowed object is
             *              {@link BigInteger }
             */
            public void setSellingPrice(BigInteger value) {
                this.sellingPrice = value;
            }

        }

    }

}
