//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.28 at 05:22:27 PM IST 
//


package io.github.soheshts.mycart.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the io.github.soheshts.mycart package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: io.github.soheshts.mycart
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Reviews }
     */
    public Reviews createReviews() {
        return new Reviews();
    }

    /**
     * Create an instance of {@link Inventory }
     */
    public Inventory createInventory() {
        return new Inventory();
    }

    /**
     * Create an instance of {@link Inventory.Category }
     */
    public Inventory.Category createInventoryCategory() {
        return new Inventory.Category();
    }

    /**
     * Create an instance of {@link Reviews.Item }
     */
    public Reviews.Item createReviewsItem() {
        return new Reviews.Item();
    }

    /**
     * Create an instance of {@link Inventory.Category.CategoryName }
     */
    public Inventory.Category.CategoryName createInventoryCategoryCategoryName() {
        return new Inventory.Category.CategoryName();
    }

    /**
     * Create an instance of {@link Inventory.Category.Item }
     */
    public Inventory.Category.Item createInventoryCategoryItem() {
        return new Inventory.Category.Item();
    }

    /**
     * Create an instance of {@link Reviews.Item.Review }
     */
    public Reviews.Item.Review createReviewsItemReview() {
        return new Reviews.Item.Review();
    }

}
